import type { Metadata } from "next";
import "@/app/globals.css";
import { Poppins } from "next/font/google";
import GoogleTagManagerScript from "@/components/layout/scripts/GoogleTagManagerScript";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{/* <GoogleTagManagerScript /> */}</head>
      <body className={`${poppins.variable} antialiased`}>{children}</body>
    </html>
  );
}
