import type { Metadata } from "next";
import { sanityFetch, SanityLive } from "@/sanity/lib/live";
import { draftMode } from "next/headers";
import { VisualEditing } from "next-sanity";
import { DisableDraftMode } from "@/components/DisableDraftMode";
import { HEADER_QUERY } from "@/queries/layout.query";
import Header from "@/components/layout/Header";
import "@/app/globals.css";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data: headerData } = await sanityFetch({ query: HEADER_QUERY });

  if (!headerData) {
    return null;
  }

  const { button, links, enableSearch } = headerData;

  const _navLinks = links?.map((link) => ({
    slug: link.link!,
    title: link.title!,
  }));

  return (
    <>
      <Header
        navItems={_navLinks}
        showSearch={enableSearch}
        button={
          button
            ? {
                slug: button.link!,
                title: button.title!,
              }
            : undefined
        }
      />
      {children}
      <Footer />
      <SanityLive />
      {(await draftMode()).isEnabled && (
        <>
          <DisableDraftMode />
          <VisualEditing />
        </>
      )}
    </>
  );
}
